import type { BidMarketCategory, BidMarketContent } from './types';

export const BID_MARKET_CATEGORIES: BidMarketCategory[] = [
  { id: 'wechat-article', label: '公众号文章' },
  { id: 'wechat-video', label: '公众号视频' },
  { id: 'document', label: '文档' },
  { id: 'other', label: '其他' },
];

export const BID_MARKET_MOCK_ITEMS: BidMarketContent[] = [
  {
    id: 'mock-policy-2026',
    title: '电网投标政策重点解读',
    kind: 'article',
    categoryId: 'wechat-article',
    categoryLabel: '公众号文章',
    summary: '梳理近期电网投标政策变化、资格审查重点与常见响应要求。',
    source: '行业资讯示例',
    typeLabel: '公众号文章',
    updatedAt: '2026-09-02',
    body: '这是用于前端界面展示的演示文章。正式上线后，标题、摘要、正文、来源和更新时间均以后端接口返回为准。',
  },
  {
    id: 'mock-video-errors',
    title: '配网设备投标常见失分点分析',
    kind: 'video',
    categoryId: 'wechat-video',
    categoryLabel: '公众号视频',
    summary: '从资格条件、技术响应和报价文件三个方面展示常见失分点。',
    source: '培训视频示例',
    typeLabel: '公众号视频',
    updatedAt: '2026-09-01',
    duration: '18:35',
    body: '这是视频资料的前端演示摘要。真实视频地址和封面需由后端接口返回。',
  },
  {
    id: 'mock-case-collection',
    title: '新能源项目投标案例汇编',
    kind: 'document',
    categoryId: 'document',
    categoryLabel: '文档',
    summary: '汇总新能源项目投标案例的结构、重点材料和复盘结论。',
    source: '案例资料示例',
    typeLabel: 'PDF 文档',
    fileType: 'PDF',
    updatedAt: '2026-08-30',
    body: '这是文档预览占位内容。后端接入后将展示实际文档预览或下载地址。',
  },
  {
    id: 'mock-response-checklist',
    title: '技术标响应检查清单',
    kind: 'document',
    categoryId: 'document',
    categoryLabel: '文档',
    summary: '用于提交前检查技术偏差、参数响应、签章和附件完整性。',
    source: '内部资料示例',
    typeLabel: 'Excel 文档',
    fileType: 'XLSX',
    updatedAt: '2026-08-28',
    body: '这是检查清单的演示预览。正式内容以后端存储文件为准。',
  },
  {
    id: 'mock-platform-update',
    title: '电子招投标平台操作更新说明',
    kind: 'article',
    categoryId: 'wechat-article',
    categoryLabel: '公众号文章',
    summary: '介绍电子招投标平台近期操作变化与文件提交注意事项。',
    source: '平台动态示例',
    typeLabel: '公众号文章',
    updatedAt: '2026-08-26',
    body: '此内容仅用于演示文章阅读界面，不代表真实政策或平台公告。',
  },
  {
    id: 'mock-quote-review',
    title: '报价策略复盘：从开标结果反推竞争区间',
    kind: 'video',
    categoryId: 'wechat-video',
    categoryLabel: '公众号视频',
    summary: '演示如何结合历史开标结果复盘报价区间与竞争策略。',
    source: '培训视频示例',
    typeLabel: '公众号视频',
    updatedAt: '2026-08-24',
    duration: '12:10',
    body: '这是视频资料的演示说明，真实播放资源需由后端提供。',
  },
  {
    id: 'mock-industry-brief',
    title: '本周电力行业信息摘要',
    kind: 'other',
    categoryId: 'other',
    categoryLabel: '其他',
    summary: '汇总一周行业动态、市场信息及值得关注的采购公告。',
    source: '行情摘要示例',
    typeLabel: '其他资料',
    updatedAt: '2026-08-22',
    body: '这是其他类资料的界面演示内容，实际数据以后端接口为准。',
  },
];
