/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/enterprise-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reusable enterprise assets */
        get: operations["listEnterpriseAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enterprise-assets/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload reusable enterprise material for automatic classification
         * @description The request intentionally has no target or project_id field.
         */
        post: operations["uploadEnterpriseAssets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enterprise-assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one reusable enterprise asset and its extracted facts */
        get: operations["getEnterpriseAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enterprise-assets/{asset_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable revisions of one enterprise asset */
        get: operations["listEnterpriseAssetRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enterprise-assets/{asset_id}/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct Agent classification with optimistic concurrency control */
        patch: operations["correctEnterpriseAssetClassification"];
        trace?: never;
    };
    "/enterprise-assets/{asset_id}/facts/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct one extracted fact and create a new enterprise-asset revision */
        patch: operations["correctEnterpriseFact"];
        trace?: never;
    };
    "/projects/{project_id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List materials belonging only to the selected project */
        get: operations["listProjectMaterials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/materials/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload material to one project event
         * @description The request intentionally has no target or enterprise_asset_id field.
         */
        post: operations["uploadProjectMaterials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-materials/{material_id}/revisions/{revision_id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read source blocks from one immutable project-material revision */
        get: operations["listProjectMaterialBlocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List versioned requirements extracted only from the selected project */
        get: operations["listProjectRequirements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/requirements/{requirement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirm or correct one versioned project requirement */
        patch: operations["mutateProjectRequirement"];
        trace?: never;
    };
    "/projects/{project_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable snapshots belonging to one project */
        get: operations["listProjectSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one immutable snapshot only when it belongs to the path project */
        get: operations["getProjectSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read sanitized task state and frozen snapshot reference */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream sanitized task progress
         * @description Only PublicTaskEvent is allowed; raw model output and tool calls are forbidden.
         */
        get: operations["streamTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List enabled review providers */
        get: operations["listReviewProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/review-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a provider against a frozen project snapshot */
        post: operations["createReviewRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-runs/{review_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one immutable review run and its evidence-backed findings */
        get: operations["getReviewRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query an external read-only history provider */
        get: operations["listHistoryPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/history/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one external history sample */
        get: operations["getHistoryPriceSample"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run deterministic local QuoteEngine
         * @description No LLM-generated numeric quote is permitted.
         */
        post: operations["createQuoteCalculation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/calculations/{calculation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a deterministic calculation or its safe no-result state */
        get: operations["getQuoteCalculation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/calculations/{calculation_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply one deterministic strategy after explicit user confirmation */
        post: operations["applyQuoteCalculation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessEnvelope: {
            /** @constant */
            code: "OK";
            message: string;
            data: unknown;
            meta?: {
                request_id: string;
                project_snapshot_id?: string;
            };
        };
        ApiError: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            request_id?: string;
            retryable: boolean;
        };
        /** @enum {string} */
        EnterpriseAssetCategory: "certificate" | "qualification" | "performance" | "personnel" | "product" | "inspection_report" | "finance" | "other";
        EnterpriseAsset: {
            asset_id: string;
            name: string;
            category: components["schemas"]["EnterpriseAssetCategory"];
            /** @enum {string} */
            status: "ingesting" | "needs_review" | "active" | "expired" | "failed";
            current_revision_id: string;
            classification_confidence: number;
            /** Format: date-time */
            expires_at?: string | null;
            facts: components["schemas"]["EnterpriseFact"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        EvidenceRef: {
            /** @enum {string} */
            source_type: "enterprise_asset" | "project_material" | "requirement" | "deliverable" | "search";
            source_revision_id: string;
            content_hash: string;
            locator: {
                page?: number;
                block_id?: string;
                node_id?: string;
                cell_range?: string;
            };
            exact_quote?: string;
            claim_id?: string;
        };
        EnterpriseFact: {
            fact_id: string;
            key: string;
            label: string;
            value: unknown;
            confidence: number;
            /** @enum {string} */
            status: "extracted" | "confirmed" | "corrected" | "conflict" | "low_confidence";
            evidence_refs: components["schemas"]["EvidenceRef"][];
        };
        EnterpriseAssetRevision: {
            revision_id: string;
            version_no: number;
            original_name: string;
            mime_type: string;
            size_bytes: number;
            sha256: string;
            /** Format: date-time */
            created_at: string;
        };
        CorrectEnterpriseAssetClassificationInput: {
            category: components["schemas"]["EnterpriseAssetCategory"];
            expected_revision_id: string;
        };
        CorrectEnterpriseFactInput: {
            value: string | number | boolean | null | unknown[] | {
                [key: string]: unknown;
            };
            expected_revision_id: string;
        };
        EnterpriseFactCorrectionResult: {
            asset_id: string;
            new_revision_id: string;
            fact: components["schemas"]["EnterpriseFact"];
        };
        EnterpriseAssetPage: {
            items: components["schemas"]["EnterpriseAsset"][];
            total: number;
            page: number;
            size: number;
        };
        EnterpriseIngestionTask: {
            task_id: string;
            asset_ids: string[];
            /** @enum {string} */
            status: "queued" | "running" | "waiting_user" | "succeeded" | "failed";
        };
        ProjectMaterialRevision: {
            revision_id: string;
            material_id: string;
            project_id: string;
            event_id: string;
            /** @enum {string} */
            event_type: "initial" | "supplement" | "clarification" | "replacement";
            version_no: number;
            original_name: string;
            mime_type: string;
            size_bytes: number;
            sha256: string;
            /** @enum {string} */
            parse_status: "uploaded" | "parsing" | "parsed" | "needs_review" | "failed";
            supersedes_revision_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ProjectMaterial: {
            material_id: string;
            project_id: string;
            name: string;
            current_revision: components["schemas"]["ProjectMaterialRevision"];
            /** Format: date-time */
            created_at: string;
        };
        ProjectMaterialPage: {
            items: components["schemas"]["ProjectMaterial"][];
            total: number;
            page: number;
            size: number;
        };
        ProjectMaterialUploadResult: {
            task_id: string;
            project_id: string;
            material_ids: string[];
            /** @constant */
            status: "queued";
        };
        DocumentBlock: {
            block_id: string;
            source_revision_id: string;
            /** @enum {string} */
            type: "title" | "paragraph" | "table" | "cell" | "image";
            page: number | null;
            index: number;
            text: string;
            confidence: number | null;
        };
        DocumentBlockPage: {
            items: components["schemas"]["DocumentBlock"][];
            total: number;
            page: number;
            size: number;
        };
        Requirement: {
            requirement_id: string;
            project_id: string;
            revision_id: string;
            /** @enum {string} */
            type: "basic_info" | "qualification" | "score_rule" | "reject_clause" | "tech_requirement" | "quote_rule" | "material_checklist" | "attachment";
            content: string;
            structured: {
                [key: string]: unknown;
            };
            confidence: number;
            /** @enum {string} */
            status: "extracted" | "needs_review" | "confirmed" | "corrected";
            evidence_refs: components["schemas"]["EvidenceRef"][];
        };
        ConfirmRequirementInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "confirm";
            expected_revision_id: string;
        };
        UpdateRequirementInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "update";
            expected_revision_id: string;
            content: string;
            structured: {
                [key: string]: unknown;
            };
        };
        RequirementMutationInput: components["schemas"]["ConfirmRequirementInput"] | components["schemas"]["UpdateRequirementInput"];
        ProjectSnapshotManifest: {
            project_material_revision_ids: string[];
            requirement_revision_ids: string[];
            enterprise_asset_revision_ids: string[];
            deliverable_version_ids: string[];
            quote_sample_snapshot_id: string | null;
        };
        ProjectSnapshot: {
            snapshot_id: string;
            project_id: string;
            /** @constant */
            status: "frozen";
            /** @enum {string} */
            reason: "task" | "review" | "check" | "export" | "manual";
            manifest: components["schemas"]["ProjectSnapshotManifest"];
            content_hash: string;
            /** Format: date-time */
            created_at: string;
        };
        ProjectSnapshotPage: {
            items: components["schemas"]["ProjectSnapshot"][];
            total: number;
            page: number;
            size: number;
        };
        Task: {
            task_id: string;
            project_id: string;
            project_snapshot_id: string | null;
            phase: string;
            /** @enum {string} */
            status: "queued" | "running" | "waiting_user" | "retrying" | "cancel_requested" | "cancelled" | "superseded" | "succeeded" | "failed" | "dead_letter";
            percent: number | null;
            public_message: string;
            error_code: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PublicTaskEvent: {
            /** @constant */
            schema_version: "1";
            event_id: string;
            sequence: number;
            task_id: string;
            project_id: string;
            phase: string;
            /** @enum {string} */
            status: "queued" | "running" | "waiting_user" | "retrying" | "cancel_requested" | "cancelled" | "superseded" | "succeeded" | "failed" | "dead_letter";
            percent: number | null;
            public_message: string;
            error_code: string | null;
            /** Format: date-time */
            occurred_at: string;
            result_refs?: {
                deliverable_ids?: string[];
                requirement_revision_ids?: string[];
                review_run_id?: string;
                quote_calculation_id?: string;
                check_id?: string;
                export_job_id?: string;
            };
        };
        ReviewProvider: {
            provider_id: string;
            name: string;
            /** @enum {string} */
            type: "api" | "sandbox_code" | "rule_engine" | "document_rule";
            version: string;
            /** @enum {string} */
            status: "available" | "degraded" | "unavailable";
            capabilities: ("score" | "risk" | "evidence" | "suggestion")[];
            allowed_data_scope: ("requirements" | "deliverables" | "enterprise_facts" | "quote_snapshot")[];
            can_execute: boolean;
        };
        CreateReviewRunInput: {
            provider_id: string;
            provider_version: string;
            project_snapshot_id: string;
            deliverable_version_ids: string[];
        };
        CreateReviewRunResult: {
            review_run_id: string;
            task_id: string;
            project_snapshot_id: string;
            /** @constant */
            status: "queued";
        };
        ReviewFinding: {
            finding_id: string;
            rule_id: string;
            rule_version: string;
            /** @enum {string} */
            outcome: "pass" | "fail" | "risk" | "unknown" | "abstain";
            score: number | null;
            confidence: number | null;
            message: string;
            suggestion: string | null;
            evidence_refs: components["schemas"]["EvidenceRef"][];
        };
        ReviewRun: {
            review_run_id: string;
            project_id: string;
            project_snapshot_id: string;
            provider_id: string;
            provider_version: string;
            deliverable_version_ids: string[];
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "invalid_response" | "timed_out";
            raw_response_hash: string | null;
            findings: components["schemas"]["ReviewFinding"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at: string | null;
        };
        HistoryPriceSample: {
            sample_id: string;
            material_name: string;
            material_code: string | null;
            spec: string | null;
            tenderer: string | null;
            region: string | null;
            win_price: string;
            currency: string;
            tax_included: boolean;
            unit: string;
            /** Format: date */
            win_date: string;
            supplier: string | null;
            source_ref: string;
        };
        HistoryQuerySnapshot: {
            /** @constant */
            read_only: true;
            provider_id: string;
            provider_version: string;
            query_snapshot_id: string;
            /** Format: date-time */
            source_updated_at: string;
            samples: components["schemas"]["HistoryPriceSample"][];
            total: number;
            page: number;
            size: number;
            normalization_warnings: string[];
        };
        QuoteCalculationInput: {
            project_snapshot_id: string;
            material_ref: string;
            cost: string;
            min_profit_rate: string;
            currency: string;
            tax_included: boolean;
            unit: string;
        };
        QuoteCalculation: components["schemas"]["CalculatedQuote"] | components["schemas"]["QuoteNeedsInput"] | components["schemas"]["InsufficientQuote"] | components["schemas"]["QuoteConstraintViolation"];
        CalculatedQuote: {
            calc_id: string;
            project_snapshot_id: string;
            algorithm_version: string;
            /** Format: date-time */
            created_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "calculated";
            query_snapshot_id: string;
            sample_snapshot_id: string;
            confidence_interval: {
                min: string;
                max: string;
            };
            normalized_input: {
                currency: string;
                tax_included: boolean;
                unit: string;
            };
            excluded_sample_count: number;
            strategies: components["schemas"]["QuoteStrategy"][];
        };
        QuoteStrategy: {
            strategy_id: string;
            /** @enum {string} */
            strategy: "win" | "balance" | "profit";
            suggested_price: string;
            score: string | null;
            gross_margin: string;
            /** @enum {string} */
            risk_level: "low" | "medium" | "high";
            basis: string[];
        };
        QuoteNeedsInput: {
            calc_id: string;
            project_snapshot_id: string;
            algorithm_version: string;
            /** Format: date-time */
            created_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "needs_input";
            missing_fields: string[];
            message: string;
        };
        InsufficientQuote: {
            calc_id: string;
            project_snapshot_id: string;
            algorithm_version: string;
            /** Format: date-time */
            created_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "insufficient_data";
            query_snapshot_id: string;
            observed_sample_count: number;
            required_sample_count: number;
            message: string;
        };
        QuoteConstraintViolation: {
            calc_id: string;
            project_snapshot_id: string;
            algorithm_version: string;
            /** Format: date-time */
            created_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "constraint_violation";
            violations: string[];
            message: string;
        };
        ApplyQuoteInput: {
            strategy_id: string;
            expected_version_id: string;
            /** @constant */
            confirmed: true;
        };
        ApplyQuoteResult: {
            deliverable_id: string;
            new_version_id: string;
            audit_log_id: string;
        };
    };
    responses: {
        /** @description Request violates a data-domain boundary */
        DomainViolation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description The expected revision/version is no longer current */
        VersionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource is unknown or does not belong to the requested project/tenant */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        AssetId: string;
        ProjectId: string;
        Page: number;
        Size: number;
        IdempotencyKey: string;
        TaskId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listEnterpriseAssets: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
                category?: components["schemas"]["EnterpriseAssetCategory"];
                status?: "ingesting" | "needs_review" | "active" | "expired" | "failed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enterprise assets only; project materials must never appear. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["EnterpriseAssetPage"];
                    };
                };
            };
        };
    };
    uploadEnterpriseAssets: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    "files[]": string[];
                    category_hint?: components["schemas"]["EnterpriseAssetCategory"];
                };
            };
        };
        responses: {
            /** @description Ingestion accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["EnterpriseIngestionTask"];
                    };
                };
            };
            422: components["responses"]["DomainViolation"];
        };
    };
    getEnterpriseAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enterprise asset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["EnterpriseAsset"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listEnterpriseAssetRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revision list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["EnterpriseAssetRevision"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    correctEnterpriseAssetClassification: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                asset_id: components["parameters"]["AssetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectEnterpriseAssetClassificationInput"];
            };
        };
        responses: {
            /** @description Corrected asset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["EnterpriseAsset"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["VersionConflict"];
        };
    };
    correctEnterpriseFact: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                asset_id: components["parameters"]["AssetId"];
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectEnterpriseFactInput"];
            };
        };
        responses: {
            /** @description Corrected fact and the newly created revision id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["EnterpriseFactCorrectionResult"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["VersionConflict"];
        };
    };
    listProjectMaterials: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project material page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ProjectMaterialPage"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    uploadProjectMaterials: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    "files[]": string[];
                    /** @enum {string} */
                    event_type: "initial" | "supplement" | "clarification" | "replacement";
                    supersedes_revision_id?: string;
                };
            };
        };
        responses: {
            /** @description Project ingestion accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ProjectMaterialUploadResult"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["DomainViolation"];
        };
    };
    listProjectMaterialBlocks: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                material_id: string;
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document block page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["DocumentBlockPage"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProjectRequirements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requirement list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["Requirement"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    mutateProjectRequirement: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
                requirement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementMutationInput"];
            };
        };
        responses: {
            /** @description New confirmed or corrected requirement revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["Requirement"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["VersionConflict"];
        };
    };
    listProjectSnapshots: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project snapshot page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ProjectSnapshotPage"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProjectSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ProjectSnapshot"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["Task"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    streamTaskEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events; each data field is a PublicTaskEvent JSON object. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listReviewProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ReviewProvider"][];
                    };
                };
            };
        };
    };
    createReviewRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRunInput"];
            };
        };
        responses: {
            /** @description Review queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["CreateReviewRunResult"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getReviewRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ReviewRun"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listHistoryPrices: {
        parameters: {
            query?: {
                material_name?: string;
                material_code?: string;
                spec?: string;
                region?: string;
                tenderer?: string;
                year?: number;
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable query snapshot; read_only is always true. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["HistoryQuerySnapshot"];
                    };
                };
            };
        };
    };
    getHistoryPriceSample: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History sample */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["HistoryPriceSample"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createQuoteCalculation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteCalculationInput"];
            };
        };
        responses: {
            /** @description Calculation result, which may be insufficient_data without any price. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["QuoteCalculation"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getQuoteCalculation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                calculation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quote calculation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["QuoteCalculation"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    applyQuoteCalculation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                calculation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyQuoteInput"];
            };
        };
        responses: {
            /** @description Quote deliverable version created with an audit record */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ApplyQuoteResult"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["VersionConflict"];
        };
    };
}
